# Generated by Django 6.0.6 on 2026-06-18 11:17

import django.db.models.deletion
import users_files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер (в байтах)')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('file', models.FileField(upload_to=users_files.models.get_file_storage_path, verbose_name='Путь к файлу в хранилище')),
                ('special_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен специальной ссылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл пользователя',
                'verbose_name_plural': 'Файлы пользователей',
                'indexes': [models.Index(fields=['special_link'], name='users_files_special_98cfed_idx')],
            },
        ),
    ]
