# Generated by Django 6.0.6 on 2026-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfiles',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
